function [municipal_name,municipal_key] = getMunicipalities()
    municipal_name = ["小諸市";"佐久市";"小海町";"佐久穂町";"川上村";"南牧村"; ...
        "南相木村";"北相木村";"軽井沢町";"御代田町";"立科町";"上田市";"東御市"; ...
        "長和町";"青木村";"岡谷市";"諏訪市";"茅野市";"下諏訪町";"富士見町"; ...
        "原村";"伊那市";"駒ケ根市";"辰野町";"箕輪町";"飯島町";"南箕輪村"; ...
        "中川村";"宮田村";"飯田市";"松川町";"高森町";"阿南町";"阿智村";"平谷村"; ...
        "根羽村";"下條村";"売木村";"天龍村";"泰阜村";"喬木村";"豊丘村";"大鹿村"; ...
        "上松町";"南木曽町";"木曽町";"木祖村";"王滝村";"大桑村";"松本市";"塩尻市"; ...
        "安曇野市";"麻績村";"生坂村";"山形村";"朝日村";"筑北村";"大町市";"池田町"; ...
        "松川村";"白馬村";"小谷村";"長野市";"須坂市";"千曲市";"坂城町";"小布施町"; ...
        "高山村";"信濃町";"飯綱町";"小川村";"中野市";"飯山市";"山ノ内町";"木島平村"; ...
        "野沢温泉村";"栄村";"松本保健所管内";"佐久保健所管内";"飯田保健所管内"; ...
        "大町保健所管内";"諏訪保健所管内";"伊那保健所管内";"上田保健所管内"; ...
        "木曽保健所管内";"北信保健所管内"];
municipal_key = {'YMD' 'KomoroCity' 'SakuCity' 'KoumiMachi' 'SakuhoMachi' 'KawakamiMura' 'MinamimakiMura' ...
        'MinamiAikiMura' 'KitaaikiMura' 'KaruizawaMachi' 'MiyotaMachi' 'TateshinaMachi' 'UedaCity'  'TomiCity' ...
        'NagawaMachi' 'AokiMura' 'OkayaCity' 'SuwaCity' 'ChinoCity' 'ShimosuwaMachi' 'FujimiMachi' ...
        'HaraMura' 'InaCity' 'KomaganeCity' 'TatsunoMachi' 'MinowaMachi' 'IijimaMachi' 'MinamiminowaMura' ...
        'NakagawaMura' 'MiyataMura' 'IidaCity' 'MatsukawaMachi' 'TakamoriMachi' 'AnanCho' 'AchiMura' 'HirayaMura' ...
        'NebaMura' 'ShimojoMura' 'UrukiMura' 'TenryuMura' 'YasuokaMura' 'TakagiMura' 'ToyookaMura' 'OoshikaMura' ...
        'AgematsuMachi' 'NagisoMachi' 'KisoMachi' 'KisoMura' 'OotakiMura' 'OokuwaMura' 'MatsumotoCity' 'ShiojiriCity' ...
        'AzuminoCity' 'OmiMura' 'IkusakaMura' 'YamagataMura' 'AsahiMachi' 'ChikuhokuMura' 'OomachiCity' 'IkedaMachi' ...
        'MatsukawaMura' 'HakubaMura' 'OtariMura' 'NaganoCity' 'SuzakaCity' 'ChikumaCity' 'SakakiMachi' 'ObuseMachi' ...
        'TakayamaMura' 'ShinanoMachi' 'IizunaMura' 'OgawaMura' 'NakanoCity' 'IiyamaCity' 'YamanouchiMachi' 'KijimadairaMura' ...
        'NozawaonsenMura' 'SakaeMura' 'MatsumotoArea' 'SakuArea' 'IidaArea' 'OomachiArea' 'SuwaArea' 'InaArea' 'UedaArea' ...
        'KisoArea' 'HokushinArea' 'Other'} ;
end